# Generated by Django 5.1.3 on 2024-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.IntegerField(default=0),
        ),
    ]
