# Generated by Django 5.1.3 on 2024-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_fat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chocolate', 'шоколадные'), ('sugar_sprinkles', 'сахарные присыпки'), ('fruits', 'фрукты'), ('syrups', 'сиропы'), ('jams', 'джемы')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fillers',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='catalog.filler'),
        ),
    ]
