# Generated by Django 5.1.3 on 2024-12-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_filler_product_fillers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chocolate', 'шоколад'), ('berry', 'ягоды'), ('mint', 'мятные'), ('citrus', 'цитрусы')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category'),
        ),
    ]
